package org.com.product.repo.entity;
// Generated May 3, 2022, 1:38:42 PM by Hibernate Tools 6.0.0.Beta2


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

import org.com.order.repo.entity.OrderProductsEntity;
import org.com.product.service.dto.ProductDto;
import org.com.product.service.dto.ProductPostDto;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name="products"
    ,catalog="myshop"
)
public class ProductsEntity  implements java.io.Serializable {

     private int id;
     private String productName;
     private String productDesc;
     private double price;
     private int categoryId;
     private int stock;
     private String imgPath;
     private Set<OrderProductsEntity> orderProductses = new HashSet<OrderProductsEntity>(0);

    public ProductsEntity() {
    }

   
    public ProductsEntity(ProductDto productDto) {
        this.id = productDto.getId();
       this.productName = productDto.getProductName();
       this.productDesc = productDto.getProductDesc();
       this.price = productDto.getPrice();
       this.categoryId = productDto.getCategoryId();
       this.stock = productDto.getStock();
       this.imgPath = productDto.getImgPath();
    //    this.orderProductses = orderProductses;
    }


    public ProductsEntity(ProductPostDto productDtoPostDto) {
        this.productName = productDtoPostDto.getProductName();
       this.productDesc = productDtoPostDto.getProductDesc();
       this.price = productDtoPostDto.getPrice();
       this.categoryId = productDtoPostDto.getCategoryId();
       this.stock = productDtoPostDto.getStock();
       this.imgPath = productDtoPostDto.getImgPath();
    }


    @Id 
    @Column(name="id", unique=true, nullable=false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public int getId() {
        return this.id;
    }
    public void setId(int id) {
        this.id=id;
    }

    
    
    
    @Column(name="product_name", nullable=false, length=65535)
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }

    
    @Column(name="product_desc", nullable=false, length=65535)
    public String getProductDesc() {
        return this.productDesc;
    }
    
    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc;
    }

    
    @Column(name="price", nullable=false, precision=22, scale=0)
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }

    
    @Column(name="category_id", nullable=false)
    public int getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }

    
    @Column(name="stock", nullable=false)
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }

    
    @Column(name="img_path", nullable=true, length=65535)
    public String getImgPath() {
        return this.imgPath;
    }
    
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="products")
    public Set<OrderProductsEntity> getOrderProductses() {
        return this.orderProductses;
    }
    
    public void setOrderProductses(Set<OrderProductsEntity> orderProductses) {
        this.orderProductses = orderProductses;
    }




}


